{{- if eq .Values.service.type "ClusterIP" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: {{ template "fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - port: 9042
    name: cql
  - port: 7199
    name: jmx
  selector:
    app: cassandra
    instance: {{ .Release.Name }}
{{- end -}}